### ISSUE TITLE
do this support udim texture ?

### ISSUE THREAD

**Issue by tomyu168** [raccoon-path/texture-packer#1]

**Comment by raccoon-path** [comment]
Not yet. But isn't difficult to implement. 
Since, in the context of working with files, UDIM is a naming convention, the implementation is simple - extract the "suffix" from the file name instead of splitting the file name into fragments. Like that (in internal representation):
 - old (current) approach: texname_suffix.png -> ["texname", "_suffix", "png"]
 - udim approach: texname_suffix.1022.png -> ["texname@SUFFIX_PLACEHOLDER@.1022","_suffix","png"]

The texture packing process remains unchanged.
After packing, replace the @SUFFIX_PLACEHOLDER@ with the required suffix, like that:
["texname@SUFFIX_PLACEHOLDER@.1022", "new_suffix","png"] -> texname_new_suffix.1022.png
I'll try to do it soon. 

P.S. Sorry for long responce time, I was on vacation.

**Comment by raccoon-path** [comment]
Done with [e313c03](https://github.com/raccoon-path/texture-packer/commit/e313c03c643bfec1f45ae173ecf824a7ee2fdd78). Now, UDIM textures and all textures with names like: name_part1[suffix].name_part2.ext are processed correctly.
